from fileinput import hook_encoded

for i in range(5, 21):
    file = open("{}.html".format(i), "w")
    file.write('<!DOCTYPE html>\n'
               '<html lang="en>\n'
               '<head>\n'
               '    <meta charset="UTF-8">\n'
               '    <title>{0}</title>\n'
               '    <link rel="stylesheet" type="text/css" href="default.css">\n'
               '</head>\n'
               '<div id="center">\n'
               '    <div>\n'
               '        <p>{0}</p><!--标题-->\n'
               '        <h3></h3><!--正文-->\n'
               '        </div>\n'
               '    </div>\n'
               '    <div>\n'
               '        <a href="{1}.html"><button>上一页,</button></a>\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'
               '        <a href="{2}.html"><button>上一页,</button></a>\n'
               '    </div>\n'
               '</div>\n'
               '</body>\n'
               '</html>\n'
               .format(i, i - 1, i+1))
